FROM node:18-alpine

RUN apk add --no-cache curl
RUN npm install -g pnpm

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
COPY .env.test .
RUN pnpm run build

EXPOSE 3000

# CMD ["pnpm", "start"]