FROM node:18-alpine

RUN apk add --no-cache curl wget bash openjdk17-jre
RUN npm install -g pnpm

# Install Flyway
RUN wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/11.14.1/flyway-commandline-11.14.1-linux-x64.tar.gz | tar xvz \
    && mv flyway-11.14.1 /opt/flyway \
    && rm -rf /opt/flyway/jre \
    && ln -s /opt/flyway/flyway /usr/local/bin/flyway

WORKDIR /test-runner

COPY wait-and-test.sh ./
RUN chmod +x wait-and-test.sh

CMD ["./wait-and-test.sh"]