name: Deploy Frontend

on:
  # push:
  #   paths:
  #     - "frontend/**"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Copy frontend build to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "frontend/dist/"
          target: "/home/${{ vars.EC2_USER }}/frontend-build/"
          rm: true

      - name: Deploy static files on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/frontend
            sudo rm -rf /var/www/frontend/*
            sudo cp -r /home/${{ vars.EC2_USER }}/frontend-build/frontend/dist/* /var/www/frontend/
            sudo chown -R nginx:nginx /var/www/frontend || true
            echo "Frontend static files deployed to /var/www/frontend."
